import { Droplets, FlaskConical, Sparkles } from 'lucide-react';

const normalizeSpecKeyPart = (value = '') => String(value || '')
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

export const getProductSpecSchemaKey = (categoryLevel2 = '', categoryLevel3 = '-') => (
    `${normalizeSpecKeyPart(categoryLevel2)}::${normalizeSpecKeyPart(categoryLevel3 || '-')}`
);

const SPEC_SCHEMA_BY_KEY = {
    [getProductSpecSchemaKey("Parfum & Wewangian", "-")]: {
        categoryLevel2: "Parfum & Wewangian",
        categoryLevel3: "-",
        title: "Spesifikasi Parfum & Wewangian",
        icon: Droplets,
        theme: {
            bg: "bg-purple-50/50 border-purple-100",
            title: "text-purple-800 border-purple-100",
            label: "text-purple-700",
            input: "border-purple-200 focus:ring-purple-500/50",
        },
        primaryFields: [
            {
                name: "jenisKelamin",
                label: "Jenis Kelamin",
                type: "searchable",
                required: true,
                options: ["Pria", "Wanita", "Unisex"],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "aroma",
                label: "Aroma (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "kondisi",
                label: "Kondisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "kelompokUsia",
                label: "Kelompok Usia",
                type: "searchable",
                options: ["Anak", "Remaja", "Dewasa", "Semua Usia"],
                colSpan: 1,
            },
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable-creatable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable-creatable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Pembersih Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Pembersih Wajah",
        title: "Spesifikasi Pembersih Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisPembersih",
                label: "Jenis Pembersih",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Toner")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Toner",
        title: "Spesifikasi Toner",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "areaPengaplikasian",
                label: "Area Pengaplikasian (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Pelembab Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Pelembab Wajah",
        title: "Spesifikasi Pelembab Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "spf",
                label: "SPF",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Facial Mist")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Facial Mist",
        title: "Spesifikasi Facial Mist",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "searchable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "text",
                placeholder: "Masukkan tipe paket...",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Serum & Essence Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Serum & Essence Wajah",
        title: "Spesifikasi Serum & Essence Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Scrub & Peel Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Scrub & Peel Wajah",
        title: "Spesifikasi Scrub & Peel Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable-creatable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Masker Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Masker Wajah",
        title: "Spesifikasi Masker Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisMasker",
                label: "Jenis Masker",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "jenisKelamin",
                label: "Jenis Kelamin",
                type: "searchable",
                options: ["Pria", "Wanita", "Unisex"],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Sunscreen Wajah")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Sunscreen Wajah",
        title: "Spesifikasi Sunscreen Wajah",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "spf",
                label: "SPF",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "komposisi",
                label: "Komposisi (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Perawatan Wajah", "Perawatan Wajah Lainnya")]: {
        categoryLevel2: "Perawatan Wajah",
        categoryLevel3: "Perawatan Wajah Lainnya",
        title: "Spesifikasi Perawatan Wajah Lainnya",
        icon: FlaskConical,
        theme: {
            bg: "bg-blue-50/50 border-blue-100",
            title: "text-blue-800 border-blue-100",
            label: "text-blue-700",
            input: "border-blue-200 focus:ring-blue-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "manfaatPerawatanBibir",
                label: "Manfaat Perawatan Bibir",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "konsentrasi",
                label: "Konsentrasi (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "quantityPerPack",
                label: "Quantity per Pack",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Body Care", "Sabun Mandi")]: {
        categoryLevel2: "Body Care",
        categoryLevel3: "Sabun Mandi",
        title: "Spesifikasi Sabun Mandi",
        icon: Sparkles,
        theme: {
            bg: "bg-emerald-50/50 border-emerald-100",
            title: "text-emerald-800 border-emerald-100",
            label: "text-emerald-700",
            input: "border-emerald-200 focus:ring-emerald-500/50",
        },
        primaryFields: [
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanTubuh",
                label: "Manfaat Perawatan Tubuh (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "handmade",
                label: "Handmade",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "jenisKemasan",
                label: "Jenis Kemasan",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Body Care", "Scrub & Peel Tubuh")]: {
        categoryLevel2: "Body Care",
        categoryLevel3: "Scrub & Peel Tubuh",
        title: "Spesifikasi Scrub & Peel Tubuh",
        icon: Sparkles,
        theme: {
            bg: "bg-emerald-50/50 border-emerald-100",
            title: "text-emerald-800 border-emerald-100",
            label: "text-emerald-700",
            input: "border-emerald-200 focus:ring-emerald-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "manfaatPerawatanTubuh",
                label: "Manfaat Perawatan Tubuh (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "areaPengaplikasian",
                label: "Area Pengaplikasian (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Body Care", "Body Cream, Body Lotion & Body Butter")]: {
        categoryLevel2: "Body Care",
        categoryLevel3: "Body Cream, Body Lotion & Body Butter",
        title: "Spesifikasi Body Cream, Body Lotion & Body Butter",
        icon: Sparkles,
        theme: {
            bg: "bg-emerald-50/50 border-emerald-100",
            title: "text-emerald-800 border-emerald-100",
            label: "text-emerald-700",
            input: "border-emerald-200 focus:ring-emerald-500/50",
        },
        primaryFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanTubuh",
                label: "Manfaat Perawatan Tubuh (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "text",
                placeholder: "Masukkan tipe khusus (max 0/5)...",
                colSpan: 1,
            },
            {
                name: "jenisEdisi",
                label: "Jenis Edisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "quantityPerPack",
                label: "Quantity per Pack",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "jenisPelembab",
                label: "Jenis Pelembab",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "spf",
                label: "SPF",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Body Care", "Deodoran")]: {
        categoryLevel2: "Body Care",
        categoryLevel3: "Deodoran",
        title: "Spesifikasi Deodoran",
        icon: Sparkles,
        theme: {
            bg: "bg-emerald-50/50 border-emerald-100",
            title: "text-emerald-800 border-emerald-100",
            label: "text-emerald-700",
            input: "border-emerald-200 focus:ring-emerald-500/50",
        },
        primaryFields: [
            {
                name: "manfaatPerawatanTubuh",
                label: "Manfaat Perawatan Tubuh (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "aroma",
                label: "Aroma (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranProduk",
                label: "Ukuran Produk",
                type: "text",
                placeholder: "Masukkan ukuran produk...",
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "text",
                placeholder: "Masukkan tipe khusus (max 0/5)...",
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "quantityPerPack",
                label: "Quantity per Pack",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal2",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
        ],
    },
    [getProductSpecSchemaKey("Body Care", "Perawatan Tubuh Lainnya")]: {
        categoryLevel2: "Body Care",
        categoryLevel3: "Perawatan Tubuh Lainnya",
        title: "Spesifikasi Perawatan Tubuh Lainnya",
        icon: Sparkles,
        theme: {
            bg: "bg-emerald-50/50 border-emerald-100",
            title: "text-emerald-800 border-emerald-100",
            label: "text-emerald-700",
            input: "border-emerald-200 focus:ring-emerald-500/50",
        },
        primaryFields: [
            {
                name: "formulasi",
                label: "Formulasi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tanggalKedaluwarsa",
                label: "Tanggal Kedaluwarsa",
                type: "date",
                colSpan: 1,
            },
            {
                name: "beratProduk",
                label: "Berat Produk",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "noIzinEdar",
                label: "No. Izin Edar (BPOM, PIRT)",
                type: "text",
                placeholder: "Masukkan no. izin edar (bpom, pirt)...",
                colSpan: 1,
            },
            {
                name: "masaPenyimpanan",
                label: "Masa Penyimpanan",
                type: "searchable-creatable",
                required: true,
                options: [],
                colSpan: 1,
            },
            {
                name: "negaraAsal",
                label: "Negara Asal",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanTubuh",
                label: "Manfaat Perawatan Tubuh (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "volume",
                label: "Volume",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
        extendedFields: [
            {
                name: "tipePaket",
                label: "Tipe Paket",
                type: "searchable",
                options: ["Single", "Bundle", "Refill"],
                colSpan: 1,
            },
            {
                name: "komposisi",
                label: "Komposisi",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "manfaatPerawatanKulit",
                label: "Manfaat Perawatan Kulit",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "ingredient",
                label: "Ingredient (Komposisi)",
                type: "text",
                placeholder: "Masukkan ingredient (komposisi)...",
                colSpan: 2,
            },
            {
                name: "ukuranPerProduk",
                label: "Ukuran Per Produk",
                type: "text",
                placeholder: "Ketik nilai...",
                colSpan: 1,
            },
            {
                name: "noSertifikasi",
                label: "No. Sertifikasi (Halal)",
                type: "text",
                placeholder: "Masukkan no. sertifikasi (halal)...",
                colSpan: 1,
            },
            {
                name: "quantityPerPack",
                label: "Quantity per Pack",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "bahanNonHalal",
                label: "Bahan Non Halal",
                type: "searchable",
                options: ["Ada", "Tidak Ada"],
                colSpan: 1,
            },
            {
                name: "jenisKulit",
                label: "Jenis Kulit (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "tipeKhusus",
                label: "Tipe Khusus (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
            {
                name: "jumlahProdukDalamKemasan",
                label: "Jumlah Produk Dalam Kemasan",
                type: "text",
                placeholder: "Masukkan jumlah produk dalam kemasan...",
                colSpan: 1,
            },
            {
                name: "produkCustom",
                label: "Produk Custom",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "mysteryBox",
                label: "Mystery Box",
                type: "searchable",
                options: ["Ya", "Tidak"],
                colSpan: 1,
            },
            {
                name: "sertifikatHalal",
                label: "Sertifikat Halal",
                type: "searchable-creatable",
                options: ["Ya", "Tidak", "Dalam Proses"],
                colSpan: 1,
            },
            {
                name: "targetArea",
                label: "Target Area (max 0/5)",
                type: "searchable-creatable",
                options: [],
                colSpan: 1,
            },
        ],
    },
};

const toNonEmptyString = (value = '') => String(value || '').trim();

const buildDummyOptions = (fieldLabel = '') => {
    const label = toNonEmptyString(fieldLabel).replace(/\(.*?\)/g, '').replace(/\*/g, '').trim();
    const lower = label.toLowerCase();

    if (lower.includes('jenis kulit')) return ['Normal', 'Kering', 'Berminyak', 'Kombinasi', 'Sensitif'];
    if (lower.includes('manfaat')) return ['Melembapkan', 'Mencerahkan', 'Menenangkan'];
    if (lower.includes('formulasi')) return ['Gel', 'Cream', 'Lotion'];
    if (lower.includes('komposisi')) return ['Natural', 'Aktif', 'Aroma'];
    if (lower.includes('ukuran')) return ['Kecil', 'Sedang', 'Besar'];
    if (lower.includes('volume')) return ['30 ml', '60 ml', '100 ml'];
    if (lower.includes('berat')) return ['100 gr', '250 gr', '500 gr'];
    if (lower.includes('negara')) return ['Indonesia', 'Korea Selatan', 'Jepang'];
    if (lower.includes('masa penyimpanan')) return ['6 Bulan', '12 Bulan', '24 Bulan'];
    if (lower.includes('spf')) return ['SPF 15', 'SPF 30', 'SPF 50'];
    if (lower.includes('jenis kelamin')) return ['Pria', 'Wanita', 'Unisex'];

    const base = label || 'Opsi';
    return [`${base} 1`, `${base} 2`, `${base} 3`];
};

const enrichFieldOptionsWithDummy = (field = {}) => {
    const supportedTypes = ['searchable', 'searchable-creatable', 'select'];
    if (!supportedTypes.includes(field.type)) return field;

    const cleanOptions = Array.isArray(field.options)
        ? field.options.map((option) => toNonEmptyString(option)).filter((option) => option !== '')
        : [];

    if (cleanOptions.length > 0) return field;

    return {
        ...field,
        options: buildDummyOptions(field.label),
    };
};

const enrichSchemaWithDummyOptions = (schema = {}) => {
    const hasLegacyFields = Array.isArray(schema.fields);
    const hasPrimaryFields = Array.isArray(schema.primaryFields);
    const hasExtendedFields = Array.isArray(schema.extendedFields);

    return {
        ...schema,
        ...(hasLegacyFields ? { fields: schema.fields.map(enrichFieldOptionsWithDummy) } : {}),
        ...(hasPrimaryFields ? { primaryFields: schema.primaryFields.map(enrichFieldOptionsWithDummy) } : {}),
        ...(hasExtendedFields ? { extendedFields: schema.extendedFields.map(enrichFieldOptionsWithDummy) } : {}),
    };
};

const ENRICHED_SPEC_SCHEMA_BY_KEY = Object.fromEntries(
    Object.entries(SPEC_SCHEMA_BY_KEY).map(([key, schema]) => [key, enrichSchemaWithDummyOptions(schema)])
);

const SPEC_SCHEMA_ENTRIES = Object.values(ENRICHED_SPEC_SCHEMA_BY_KEY).map((schema) => ({
    l2Key: normalizeSpecKeyPart(schema.categoryLevel2),
    l3Key: normalizeSpecKeyPart(schema.categoryLevel3 || '-'),
    schema,
}));

export const resolveProductSpecSchema = (schemaMap, {
    catL2Id = '',
    catL3Id = '',
    categoryLevel2Name = '',
    categoryLevel3Name = '-',
} = {}) => {
    if (!schemaMap) return null;

    const level2Key = normalizeSpecKeyPart(categoryLevel2Name);
    const level3Key = normalizeSpecKeyPart(categoryLevel3Name || '-');
    const hasCategoryNames = level2Key !== '';
    if (hasCategoryNames) {
        const exactByName = schemaMap[getProductSpecSchemaKey(categoryLevel2Name, categoryLevel3Name || '-')];
        if (exactByName) return exactByName;
    }

    const schemaByCatL3Id = schemaMap[catL3Id];
    if (schemaByCatL3Id) return schemaByCatL3Id;

    const schemaByCatL2Id = schemaMap[catL2Id];
    if (schemaByCatL2Id && !hasCategoryNames) return schemaByCatL2Id;

    if (!hasCategoryNames) return schemaByCatL2Id || null;

    const level2Default = schemaMap[getProductSpecSchemaKey(categoryLevel2Name, '-')];
    const candidates = SPEC_SCHEMA_ENTRIES.filter((item) => item.l2Key === level2Key);

    if (candidates.length > 0) {
        const exactLevel3 = candidates.find((item) => item.l3Key === level3Key);
        if (exactLevel3) return exactLevel3.schema;

        const containsLevel3 = candidates.find((item) => (
            item.l3Key.includes(level3Key) || level3Key.includes(item.l3Key)
        ));
        if (containsLevel3) return containsLevel3.schema;

        const level3Tokens = level3Key.split('-').filter(Boolean);
        if (level3Tokens.length > 0) {
            let bestCandidate = null;
            let bestScore = 0;

            candidates.forEach((item) => {
                const itemTokens = item.l3Key.split('-').filter(Boolean);
                const score = level3Tokens.filter((token) => itemTokens.includes(token)).length;
                if (score > bestScore) {
                    bestScore = score;
                    bestCandidate = item;
                }
            });

            if (bestCandidate && bestScore > 0) {
                return bestCandidate.schema;
            }
        }
    }

    return level2Default || null;
};

export const PRODUCT_SPEC_SCHEMA = {
    11: ENRICHED_SPEC_SCHEMA_BY_KEY[getProductSpecSchemaKey('Parfum & Wewangian', '-')],
    12: ENRICHED_SPEC_SCHEMA_BY_KEY[getProductSpecSchemaKey('Perawatan Wajah', 'Perawatan Wajah Lainnya')],
    13: ENRICHED_SPEC_SCHEMA_BY_KEY[getProductSpecSchemaKey('Body Care', 'Perawatan Tubuh Lainnya')],

    [getProductSpecSchemaKey('Perawatan Wajah', '-')]: ENRICHED_SPEC_SCHEMA_BY_KEY[getProductSpecSchemaKey('Perawatan Wajah', 'Perawatan Wajah Lainnya')],
    [getProductSpecSchemaKey('Body Care', '-')]: ENRICHED_SPEC_SCHEMA_BY_KEY[getProductSpecSchemaKey('Body Care', 'Perawatan Tubuh Lainnya')],

    ...ENRICHED_SPEC_SCHEMA_BY_KEY,
};
